name: "Set AWS Credentials"
description: "Set AWS Credentials"

author: Finisterra-io

branding:
  icon: "terminal"
  color: "blue"

inputs:
  folder:
    description: "Folder to use to parse and get credentials"
    required: true

runs:
  using: "composite"
  steps:
    - name: Extract AWS Information from Folder
      id: extract-info
      shell: bash
      run: |
        AWS_ACCOUNT_ID=$(echo "${{ inputs.folder }}" | awk -F'/' '{print $4}')
        AWS_REGION=$(echo "${{ inputs.folder }}" | awk -F'/' '{print $5}')
        if [[ "$AWS_REGION" == "global" ]]; then
          AWS_REGION="us-east-1"
        fi
        echo "AWS_REGION=$AWS_REGION" >> $GITHUB_ENV
        echo "AWS_ROLE=arn:aws:iam::$AWS_ACCOUNT_ID:role/gha-cicd" >> $GITHUB_ENV

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ env.AWS_ROLE }}
        role-duration-seconds: 3600
